# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='country',
        ),
    ]
