# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-21 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liked', '0002_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
