# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='photos',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
