# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0003_auto_20171123_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='photos',
            new_name='03b2554e92083b96ea1960f579cecfdcd62d4ac4',
        ),
    ]
