# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0005_auto_20171202_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='2aeaa3ba8a9035c1be7f7f48d0f16186a7906424',
        ),
        migrations.AddField(
            model_name='photos',
            name='photos',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
