# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import inst.models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0008_auto_20171202_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='photos',
        ),
        migrations.AddField(
            model_name='photos',
            name='photo',
            field=models.ImageField(default=1),
            preserve_default=False,
        ),
    ]
