# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0009_auto_20171202_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('web_site', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
