# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0011_usersettings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='date_of_birth',
            field=models.DateField(default='1980-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email',
            field=models.EmailField(default="someemail@test.com", max_length=254),
            preserve_default=False,
        ),
    ]
