# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0012_auto_20171203_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='email',
        ),
    ]
