# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0013_auto_20171203_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
