# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0014_usersettings_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='avatar',
        ),
    ]
