# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0015_remove_usersettings_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='web_site',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
