# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import inst.models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0018_auto_20180219_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.FileField(blank=True),
        ),
    ]
