# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import inst.models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0019_auto_20180220_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, upload_to=inst.models.get_name_and_path),
        ),
    ]
