# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 20:02
from __future__ import unicode_literals

from django.db import migrations
import inst.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0020_auto_20180306_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True),
        ),
    ]
