# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0022_auto_20180308_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, upload_to='0c80fcbf882af3965b04422cbf46aae15f52ddaa.jpegmedia/crop_x1'),
        ),
    ]
