# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0023_auto_20180312_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, upload_to='crop_x1'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(blank=True, default='Default-image.jpeg', upload_to='crop_x0.5'),
        ),
    ]
