# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-15 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0024_auto_20180312_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='crop_x1',
            field=models.ImageField(default='', upload_to='media/photos/crop_x1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(blank=True, default='Default-image.jpeg', upload_to='crop_x0.5-'),
        ),
    ]
