# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0025_auto_20180315_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='crop_x1',
        ),
    ]
