# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0026_remove_photos_crop_x1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to=b''),
        ),
    ]
