# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0029_auto_20180326_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
