# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0040_auto_20180403_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='default_avatar',
            field=models.ImageField(default='Default-image.jpeg', upload_to=b''),
        ),
    ]
