# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0042_auto_20180403_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, default='Png.png', upload_to=''),
        ),
    ]
