# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inst', '0056_auto_20180419_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userfollowers',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='userfollowers',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='UserFollowers',
        ),
    ]
