# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0058_friend_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='likes',
        ),
        migrations.AddField(
            model_name='photos',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(blank=True, default='Default-image.jpeg', upload_to=''),
        ),
    ]
