# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import inst.models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0059_auto_20180424_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(blank=True, default='Default-image.jpeg', upload_to=''),
        ),
    ]
