# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inst', '0060_auto_20180424_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='like',
        ),
    ]
