# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0062_auto_20180426_1450'),
    ]

