# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-21 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0068_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(related_name='friend_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
