# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-21 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0073_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='current_user',
            new_name='from_friend',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='users',
            new_name='to_friend',
        ),
    ]
