# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-21 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inst', '0074_auto_20180521_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='amont',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('to_friend', 'from_friend')]),
        ),
    ]
